repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [--exclude, SC1017]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.5'
    hooks:
      - id: ruff
        args: [--fix]
